export default {
  // 商品详情
  product: '/admin/toB/product/product.jhtml',
  // 加入购物车
  cartItem: '/admin/toB/cart/cartItem.jhtml',
  // 查看购物车
  productList: '/admin/toB/cart/cartItems.jhtml',
  // 代理商立即购买
  fillInAgent: '/admin/purchaseOrder/agent/fillIn.jhtml',
  // 集团店立即购买
  fillIn: '/admin/purchaseOrder/purchaser/fillIn.jhtml',
  // 代理商计算
  calculateAgent: '/admin/purchaseOrder/agent/calculate.jhtml',
  // 集团店计算
  calculate: '/admin/purchaseOrder/purchaser/calculate.jhtml',
  // 代理商提交订单
  createOrderAgent: '/admin/purchaseOrder/agent/order.jhtml',
  // 集团店提交订单
  createOrder: '/admin/purchaseOrder/purchaser/order.jhtml',
  // 更新订单
  purchaseOrder: '/admin/purchaseOrder/order.jhtml',
  // 会员卡余额支付
  balancePayment: '/admin/purchaseOrder/balancePayment.jhtml',
  // 地址列表
  receiverList: '/admin/toB/receiver/list.jhtml',
  // 保存地址
  receiver: '/admin/toB/receiver/receiver.jhtml',
  // 发票列表
  invoiceInfos: '/admin/toB/invoiceInfo/invoiceInfos.jhtml',
  // 保存发票
  invoiceInfo: '/admin/toB/invoiceInfo/invoiceInfo.jhtml',
  // 查询订单详情
  queryOrder: '/admin/purchaseOrder/order.jhtml',
  // 获取我的发票信息
  myInvoice: 'rest/invoice/invoice.jhtml',
  // 订单追踪
  orderLogs: '/admin/purchaseOrder/logs.jhtml',
  // 物流追踪
  logistics: '/admin/purchaseOrder/logistics.jhtml',
  // 提交退款申请
  refunds: '/admin/invoicing/purchase/refunds/refunds.jhtml',
  refundsByOrderItemId: '/admin/invoicing/purchase/refunds/refundsByOrderItemId.jhtml',
  refundsByOrderId: '/admin/invoicing/purchase/refunds/refundsByOrderId.jhtml',
  // 申请发票
  applyInvoice: '/admin/invoice/purchaseOrder/invoice/apply.jhtml',
  // 根据订单查看发票
  invoiceByOrder: '/admin/invoice/purchaseOrder/invoiceByOrder.jhtml',
  // 商品分类
  productCategories: '/admin/toB/product/productCategories.jhtml',
  // 商品列表
  getList: '/admin/toB/product/list.jhtml',
  // 代理商采购订单列表
  purchaseOrderListAgent: '/admin/purchaseOrder/agent/orders.jhtml',
  // 集团店采购订单列表
  purchaseOrderList: '/admin/purchaseOrder/purchaser/orders.jhtml',
  // 内部转账
  internalTransferPayment: '/admin/purchaseOrder/internalTransferPayment.jhtml',
  // 供应商列表
  cooperationInfos: '/admin/cooperationInfo/cooperationInfos.jhtml',
  // 创建评价
  review: '/admin/purchaseOrder/review.jhtml',
  // 查看评价
  reviews: '/admin/purchaseOrder/reviews.jhtml',
  // 提交物流信息
  returns: '/admin/invoicing/purchase/refunds/returns.jhtml',
  // 查询物流公司
  deliveryCorpsByType: '/admin/delivery_corp/deliveryCorpsByType.jhtml',
  // 代理商申请列表
  agentPurchaseApplies: '/admin/invoicing/purchase/agentPurchaseApplies.jhtml',
  // 创建代理商申请
  agentPurchaseApplie: '/admin/invoicing/purchase/agentPurchaseApplie.jhtml'
};
