export default {
  // 车友会列表
  motoristsClub: '/admin/space/fleet/list.jhtml',
  // 车友会成员
  motoristsClubMember: '/admin/space/fleetMember/list.jhtml',
  // 创建车友会动态
  publistDynamic: '/admin/space/create.jhtml',
  // 更新车友会动态
  updateDynamic: '/admin/space/json/update.jhtml',
  // 车友会动态详情
  selectDynamic: '/admin/space/query.jhtml',
  // 点赞车友会动态
  thumbsUp: '/admin/space/support.jhtml',
  // 置顶车友会动态
  top: '/admin/space/top.jhtml',
  // 推荐动态
  recommend: '/admin/space/recommend.jhtml',
  // 删除车友会动态
  delete: '/admin/space/delete.jhtml',
  // 回复车友会动态
  comment: '/admin/space/comment.jhtml',
  // 车友会动态评论列表
  commentList: '/admin/space/spaceComment/list.jhtml',
  // 删除车友会动态评论
  deleteCommnet: '/admin/space/spaceComment/delete.jhtml',
  // 点赞车友会动态评论
  supportComment: '/admin/space/comment/support.jhtml',
  // 文章分类
  articleTypeList: '/admin/space/json/listArticleCatogery.jhtml',
  // 文章列表
  articleList: '/admin/space/json/listArticle.jhtml',
  // 更新话题
  updateTopic: '/admin/space/topic/update.jhtml',
  // 话题详情
  seleteTopic: '/admin/space/topic/query.jhtml',
  // 话题列表
  topicList: '/admin/space/topic/list.jhtml',
  // 删除话题
  topicDelete: '/admin/space/topic/delete.jhtml',
  // 置顶话题
  topicTop: '/admin/space/topic/top.jhtml',
  // 推荐话题
  topicRecommend: '/admin/space/topic/recommend.jhtml',
  // 车友会动态kpi
  kpi: '/admin/space/querySpaceKpi.jhtml',
  // 栏目设置列表
  communityColumns: '/admin/communityColumn/communityColumns.jhtml',
  // 获取可见栏目设置列表
  visibleColumns: '/admin/space/communityColumns.jhtml',
  // 更新社区栏目
  updateColumn: '/admin/communityColumn/communityColumn.jhtml',
  // 车友会动态列表
  dynamicList: '/admin/space/spaces.jhtml',
  // 创建动态与文章
  createDynamic: '/admin/space/space.jhtml',
  // 新增问答
  createTopic: '/admin/space/topic.jhtml',
  // 获取文章信息
  articleInfo: '/admin/space/article.jhtml'
};
